Added Register and Login files
dylancoffey99/CS4125-Wholesaler-System-Iridium pull request #5
Opened 2021-11-03 19:07 UTC by nadinefrawley

2021-11-03 20:52 UTC, dylancoffey99 requested changes
I think these files should also be put in the authentication package instead.

2021-11-03 20:52 UTC, dylancoffey99 commented on system/models/users/register.py
> +    def ask_user_credentials(self):
Make sure to type cast the return value with "def ask_user_credentials(self): -> return value type"
Although this implementation looks like its only temporary so thats fine for now.

2021-11-03 20:52 UTC, dylancoffey99 commented on system/models/users/login.py
> +    def __init__(self, user_id: int, user_name: str, password: str, is_admin: bool, error: str):
I'm not 100% sure on how this implementation will work but the login/register should pass in a User object, initialise it as well as a UserDB (hasn't been merged yet, waiting for a review). These are then used for the various authentication methods.

So I think something like this:
def __init__(self, user: User):
    self._user = user
    self._user_db = UserDB("userDB")

2021-11-05 13:10 UTC, Miracle2001 commented
I agree with Dylan.

2021-11-08 02:21 UTC, dylancoffey99 commented
I'm going to close this pull request as its too outdated and doesn't incorporate the MVC pattern. I think it's better to merge my latest pull request to the master, and start over again:

https://github.com/dylancoffey99/CS4125-Wholesaler-System-Iridium/pull/12

2021-11-08 02:21 UTC, closed without merging